[build]
  command = "npm run build:netlify"
  publish = "dist/VirniAngularStore/browser"

[build.environment]
  NODE_VERSION = "20"
  SITE_URL = "https://virni.top/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
